CREATE DATABASE PRETCC;
USE PRETCC;

CREATE TABLE TB_FUNCIONARIO (
    ID_FUNCIONARIO        INT PRIMARY KEY AUTO_INCREMENT,
    NM_PSICOLOGO           VARCHAR (100),
    DS_EMAIL             VARCHAR (100),
    DS_SENHA            VARCHAR (100)
);

CREATE TABLE TB_AGENDAMENTO ( 
    ID_AGENDAMENTO         INT PRIMARY KEY AUTO_INCREMENT,
    NM_PACIENTE         VARCHAR (100),
    DS_CPF                 VARCHAR(14),
    DT_NASCIMENTO         DATE,
    HR_AGENDAMENTO         TIME,
    DT_CONSULTA        DATE,
    DS_TELEFONE            VARCHAR (100),
    DS_SITUACAO            VARCHAR (100)
);